'use client'
import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {ColorModeScript} from '@chakra-ui/react'
import theme from '@/lib/theme'
const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <html lang="en">
    <head>
      <title>api diff</title>
    </head>
      <body className={inter.className}>
      <ColorModeScript initialColorMode={theme.config.initialColorMode} />
      {children}</body>
    </html>

  )
}
